In [1]:
# 1. Searching for a Pattern:

import re # Import the re module to work with regular expressions

text = "The rain in Spain" # Sample text
result = re.search(r"\bS\w+", text) # Search for words starting with "S"
if result:
    print(result.group()) # Print the matched word if found

Spain


In [2]:
# 2. Finding All Matches:

import re

text = "The rain in Spain" # Sample text
result = re.findall(r"\b\w+ain\b", text) # Find all words ending with 'ain'
print(result) # Print the list of matched words

['rain', 'Spain']


In [3]:
# 3. Replacing Text:
import re

text = "The rain in Spain" # Sample text
text = re.sub(r"rain", "sunshine", text) # Replace 'rain' with 'sunshine'
print(text) # Print the modified text

The sunshine in Spain


In [4]:
# 1. Creating Arrays:
import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
print(array) # Print the array

[1 2 5 4]


In [5]:
# 2. Array Computations:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
result = array - 5 # Sub 5 to each element of the array
print(result) # Print the resulting array

[-4 -3  0 -1]


In [6]:
# Aggregations
# 1. Sum:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
total = np.sum(array) # Compute the sum of the array elements
print(total) # Print the sum


12


In [7]:
# 2. Array Computations:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
result = array - 5 # Sub 5 to each element of the array
print(result) # Print the resulting array


[-4 -3  0 -1]


In [8]:
# 1. Sum:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
total = np.sum(array) # Compute the sum of the array elements
print(total) # Print the sum

12


In [9]:
# 2. Mean :

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
mean_value = np.mean(array)    # Compute the mean of the array elements
print(mean_value)            # Print the mean

3.0


In [10]:
# Max : 

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
max_value = np.max(array) # Compute the maximum value in the array
print(max_value) # Print the maximum value

5


In [11]:
# Mul :

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
result = array * 2 # Multiply each element of the array by 2
print(result) # Print the resulting array

[ 2  4 10  8]


In [12]:
# 2. Square:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
squared = array ** 2 # Square each element of the array
print(squared) # Print the squared array

[ 1  4 25 16]


In [13]:
# 1. Greater Than:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
comparison = array > 2 # Compare each element to see if it&#39;s greater
# than 2
print(comparison) # Print the boolean array

[False False  True  True]


In [14]:
# 2. Equality:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
equality = array == 3 # Check if each element is equal to 3
print(equality) # Print the boolean array

[False False False False]


In [15]:
# 1. Creating a Mask:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
mask = array > 2 # Create a mask for elements greater than 2
print(mask) # Print the mask

[False False  True  True]


In [16]:
# 2. Using a Mask:

import numpy as np # Import the NumPy library
array = np.array([1,2,5,4]) # Create a NumPy array
mask = array > 2 # Create a mask for elements greater than 2
print(mask) # Print the mask
filtered = array[mask] # Use the mask to filter the array
print(filtered) # Print the filtered array

[False False  True  True]
[5 4]


In [17]:
# 1. Boolean Array Creation:

import numpy as np # Import the NumPy library

array = np.array([1, 2, 5, 4]) # Create a NumPy array

bool_array = np.array([True, False, True, True]) # Create a boolean array with the same length
print(bool_array) # Print the boolean array

# 2. Using Boolean Arrays:
result = np.where(bool_array, array, -1) # Replace True values with array elements and False values with -1
print(result) # Print the resulting array

[ True False  True  True]
[ 1 -1  5  4]


In [18]:
# 1. Find all email addresses in a text:


import re # Import the re module
text = "Please contact us at support@example.com or sales@example.com"
# Sample text
emails = re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', text) # Find all email addresses
print(emails) # Print the list of email addresses

['support@example.com', 'sales@example.com']


In [19]:
# 2. Validate a phone number (format: XXX-XXX-XXXX):


import re # Import the re module
# phone_number = "123-456-7890" # Sample phone number

print("Number format accepted: 123-456-7890")
phone_number = input("Enter the phone No. : ") # Take input from the user


if re.match(r'^\d{3}-\d{3}-\d{4}$', phone_number): # Check if the phone number matches the pattern
    print("Valid phone number") # Print if valid
else:
    print("Invalid phone number") # Print if invalid

Number format accepted: 123-456-7890
Invalid phone number


In [20]:
# Phone number checking different formate

import re

def validate_phone_number():
    print("Number format accepted: 123-456-7890")
    phone_number = input("Enter the phone number: ")

    pattern = r'^\d{3}-\d{3}-\d{4}$'
    if re.match(pattern, phone_number):
        print("Valid phone number")
    else:
        print("Invalid phone number")

validate_phone_number()

Number format accepted: 123-456-7890
Invalid phone number


In [21]:
# 1. Create a 3x3 matrix and perform basic operations:

import numpy as np # Import the NumPy library
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Create a 3x3 matrix
print("Original matrix:\n", matrix) # Print the original matrix

# Element-wise addition
result_add = matrix + 10 # Add 10 to each element
print("Matrix after adding 10:\n", result_add) # Print the resulting matrix

# Element-wise multiplication
result_mul = matrix * 2 # Multiply each element by 2
print("Matrix after multiplying by 2:\n", result_mul) # Print the resulting matrix

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix after adding 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Matrix after multiplying by 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [22]:
# 2. Compute sum, mean, and maximum of an array:

import numpy as np # Import the NumPy library

array = np.array([1, 2, 3, 4, 5]) # Create a NumPy array
print("Original array:", array) # Print the original array Compute sum

total = np.sum(array) # Compute the sum of the array elements
print("Sum of array elements:", total) # Print the sum Compute mean

mean_value = np.mean(array) # Compute the mean of the array elements
print("Mean of array elements:", mean_value) # Print the mean Compute maximum

max_value = np.max(array) # Compute the maximum value in the array
print("Maximum value in array:", max_value) # Print the maximum value

Original array: [1 2 3 4 5]
Sum of array elements: 15
Mean of array elements: 3.0
Maximum value in array: 5


In [23]:
# 1. Filter elements greater than a given value:

import numpy as np # Import the NumPy library

array = np.array([10, 15, 20, 25, 30]) # Create a NumPy array
print("Original array:", array) # Print the original array

mask = array > 20 # Create a mask for elements greater than 20
print("Mask for elements > 20:", mask) # Print the mask

filtered = array[mask] # Use the mask to filter the array
print("Filtered array:", filtered) # Print the filtered array

Original array: [10 15 20 25 30]
Mask for elements > 20: [False False False  True  True]
Filtered array: [25 30]


In [24]:
# 2. Replace elements based on a condition:

import numpy as np # Import the NumPy library

array = np.array([1, 2, 3, 4, 5]) # Create a NumPy array
print("Original array:", array) # Print the original array

bool_array = array % 2 == 0 # Create a boolean array for even elements
print("Boolean array for even elements:", bool_array) # Print the boolean array

result = np.where(bool_array, array, -1) # Replace even elements with themselves and odd elements with -1
print("Resulting array:", result) # Print the resulting array

Original array: [1 2 3 4 5]
Boolean array for even elements: [False  True False  True False]
Resulting array: [-1  2 -1  4 -1]


In [25]:
# 1. Count the number of True values in a boolean array:

import numpy as np # Import the NumPy library

bool_array = np.array([True, False, True, True, False]) # Create a boolean array

print("Boolean array:", bool_array) # Print the boolean array
true_count = np.sum(bool_array) # Count the number of True values

print("Number of True values:", true_count) # Print the count of True values

Boolean array: [ True False  True  True False]
Number of True values: 3


In [26]:
# 2. Logical operations on boolean arrays:

import numpy as np # Import the NumPy library
bool_array1 = np.array([True, False, True]) # Create the first boolean array
bool_array2 = np.array([False, True, True]) # Create the second boolean array

print("Boolean array 1:", bool_array1) # Print the first boolean array
print("Boolean array 2:", bool_array2) # Print the second boolean array

# Logical AND operation
and_result = np.logical_and(bool_array1, bool_array2) # Perform  the logical AND operation
print("Logical AND result:", and_result) # Print the result of logical  AND operation

# Logical OR operation
or_result = np.logical_or(bool_array1, bool_array2) # Perform logical OR operation
print("Logical OR result:", or_result) # Print the result of logical OR

Boolean array 1: [ True False  True]
Boolean array 2: [False  True  True]
Logical AND result: [False False  True]
Logical OR result: [ True  True  True]
