In [1]:
# Program 1: Creating and Manipulating Arrays

import numpy as np

# Creating a NumPy array from a list
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:")
print(arr)

# Accessing elements of the array
print("Accessing Elements:")
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing the array
print("Slicing the Array:")
print("Elements from index 1 to 3:", arr[1:4])

Original Array:
[1 2 3 4 5]
Accessing Elements:
First element: 1
Last element: 5
Slicing the Array:
Elements from index 1 to 3: [2 3 4]


In [2]:
# Program 2: Basic Operations on Arrays

import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition of arrays
addition = arr1 + arr2
print("Array Addition:")
print(addition)

# Element-wise multiplication
multiplication = arr1 * arr2
print("Array Multiplication:")
print(multiplication)

# Dot product
dot_product = np.dot(arr1, arr2)
print("Dot Product:")
print(dot_product)

Array Addition:
[5 7 9]
Array Multiplication:
[ 4 10 18]
Dot Product:
32


In [3]:
# Program 3: Matrix Operations

import numpy as np

# Creating matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix are
print("First Matrix is :")
print(matrix1)
print("2nd Matrix is :")
print(matrix2)

# Matrix multiplication
matrix_product = np.matmul(matrix1, matrix2)
print("Matrix Multiplication:")
print(matrix_product)

# Transpose of a matrix
transpose_matrix1 = np.transpose(matrix1)
print("Transpose of Matrix1:")
print(transpose_matrix1)

transpose_matrix2 = np.transpose(matrix2)
print("Transpose of Matrix2:")
print(transpose_matrix2)

First Matrix is :
[[1 2]
 [3 4]]
2nd Matrix is :
[[5 6]
 [7 8]]
Matrix Multiplication:
[[19 22]
 [43 50]]
Transpose of Matrix1:
[[1 3]
 [2 4]]
Transpose of Matrix2:
[[5 7]
 [6 8]]


In [4]:
# 1. Sum of a List

# This program calculates the sum of all elements in a list.

# Program to calculate the sum of all elements in a list

# Define the list of numbers
numbers = [10, 20, 30, 40, 50]

# Calculate the sum using the built-in sum() function
total_sum = sum(numbers)

# Print the result
print(f"The sum of the list is: {total_sum}")

# Output: The sum of the list is: 150

The sum of the list is: 150


In [5]:
# 2. Average of a List
# This program calculates the average of all elements in a list.

# Program to calculate the average of all elements in a list

# Define the list of numbers
numbers = [10, 20, 30, 40, 50]

# Calculate the sum of the list
total_sum = sum(numbers)

# Calculate the number of elements in the list
count = len(numbers)

# Calculate the average
average = total_sum / count

# Print the result
print(f"The average of the list is: \n{average}")

# Output: The average of the list is: 30.0

The average of the list is: 
30.0


In [6]:
# 3. Maximum and Minimum of a List
# This program finds the maximum and minimum values in a list.

# Program to find the maximum and minimum values in a list

# Define the list of numbers
numbers = [10, 20, 30, 40, 50]

# Find the maximum value using the built-in max() function
max_value = max(numbers)

# Find the minimum value using the built-in min() function
min_value = min(numbers)

# Print the results
print(f"The maximum value in the list is: {max_value}")
print(f"The minimum value in the list is: {min_value}")


# Output:
# The maximum value in the list is: 50
# The minimum value in the list is: 10

The maximum value in the list is: 50
The minimum value in the list is: 10


In [7]:
# 4. Count of Elements Greater Than a Threshold
# This program counts the number of elements in a list that are greater than a specified threshold.

# Program to count the number of elements greater than a threshold

# Define the list of numbers
numbers = [10, 20, 30, 40, 50]

# Define the threshold
threshold = 25

# Use list comprehension to filter elements greater than the threshold
greater_than_threshold = [num for num in numbers if num > threshold]

# Count the elements
count = len(greater_than_threshold)

# Print the result
print(f"The number of elements greater than {threshold} is: {count}")


# Output: The number of elements greater than 25 is: 3

The number of elements greater than 25 is: 3


In [8]:
# 5. Product of a List
# This program calculates the product of all elements in a list.

# Program to calculate the product of all elements in a list

# Import the reduce function from the functools module
from functools import reduce

# Define the list of numbers
numbers = [1, 2, 3, 4, 5]

# Calculate the product using the reduce() function and a lambda function
product = reduce(lambda x, y: x * y, numbers)

# Print the result
print(f"The product of the list is: {product}")


# Output: The product of the list is: 120

The product of the list is: 120


In [9]:
# 1. Sum of All Elements in an Array

import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Calculate the sum of all elements
sum_of_elements = np.sum(array)

# Print the result
print(f"Sum of all elements: {sum_of_elements}")

# OUTPUT :
# Sum of all elements: 15

Sum of all elements: 15


In [10]:
# 2. Mean of an Array

import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Calculate the mean of the array
mean_of_array = np.mean(array)

# Print the result
print(f"Mean of the array: {mean_of_array}")

# OUTPUT :
# Mean of the array: 3.0

Mean of the array: 3.0


In [11]:
# 3. Standard Deviation of an Array

import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Calculate the standard deviation of the array
std_deviation = np.std(array)

# Print the result
print(f"Standard Deviation of the array: {std_deviation}")

#  OUTPUT :
# Standard Deviation of the array: 1.4142135623730951

Standard Deviation of the array: 1.4142135623730951


In [12]:
# 4. Adding Two Arrays Element-wise

import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Add the two arrays element-wise
sum_array = np.add(array1, array2)

# Print the result
print(f"Sum of arrays: {sum_array}")

# OUTPUT :
# Sum of arrays: [11 22 33 44 55]

Sum of arrays: [11 22 33 44 55]


In [13]:
# 5. Multiplying Two Arrays Element-wise

import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Multiply the two arrays element-wise
product_array = np.multiply(array1, array2)

# Print the result
print(f"Product of arrays: {product_array}")

# OUTPUT
# Product of arrays: [ 10  40  90 160 250]

Product of arrays: [ 10  40  90 160 250]


In [14]:
# 6. Dot Product of Two Arrays

import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Calculate the dot product of the two arrays
dot_product = np.dot(array1, array2)

# Print the result
print(f"Dot product of arrays: {dot_product}")

# OUTPUT :
# Dot product of arrays: 32

Dot product of arrays: 32


In [15]:
# 7. Transpose of a Matrix

import numpy as np

# Create a 2x3 NumPy matrix (2D array)
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the matrix
transpose_matrix = np.transpose(matrix)

# Print the result
print("Original matrix:")
print(matrix)
print("Transposed matrix:")
print(transpose_matrix)

# OUTPUT : 
# Original matrix:
# [[1 2 3]
#  [4 5 6]]
# Transposed matrix:
# [[1 4]
#  [2 5]
#  [3 6]]

Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]


In [16]:
# 8. Inverse of a Matrix

import numpy as np

# Create a 2x2 NumPy matrix (2D array)
matrix = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

# Print the result
print("Original matrix:")
print(matrix)
print("Inverse matrix:")
print(inverse_matrix)

# OUTPUT
# Original matrix:
# [[1 2]
#  [3 4]]
# Inverse matrix:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

Original matrix:
[[1 2]
 [3 4]]
Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# 9. Determinant of a Matrix

import numpy as np

# Create a 2x2 NumPy matrix (2D array)
matrix = np.array([[1, 2], [3, 4]])

# Calculate the determinant of the matrix
determinant = np.linalg.det(matrix)

# Print the result
print("Original matrix:")
print(matrix)
print(f"Determinant of the matrix: {determinant}")

# OUTPUT :
# Original matrix:
# [[1 2]
#  [3 4]]
# Determinant of the matrix: -2.0000000000000004

Original matrix:
[[1 2]
 [3 4]]
Determinant of the matrix: -2.0000000000000004


In [18]:
# 10. Element-wise Comparison of Two Arrays

import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compare the two arrays element-wise
comparison = np.equal(array1, array2)

# Print the result
print("Element-wise comparison:")
print(comparison)

# OUTPUT 
# Element-wise comparison:
# [False False  True False False]

Element-wise comparison:
[False False  True False False]


In [19]:
# 1. Compare Two Arrays for Equality

import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([1, 2, 3, 4, 5])

# Check if both arrays are equal
are_equal = np.array_equal(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Are both arrays equal?", are_equal)

# OUTPUT :
# Array 1: [1 2 3 4 5]
# Array 2: [1 2 3 4 5]
# Are both arrays equal? True

Array 1: [1 2 3 4 5]
Array 2: [1 2 3 4 5]
Are both arrays equal? True


In [20]:
# 2. Element-wise Comparison of Two Arrays

import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([1, 2, 0, 4, 5])

# Element-wise comparison
comparison = np.equal(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise comparison:", comparison)

# # OUTPUT :
# Array 1: [1 2 3 4 5]
# Array 2: [1 2 0 4 5]
# Element-wise comparison: [ True  True False  True  True]

Array 1: [1 2 3 4 5]
Array 2: [1 2 0 4 5]
Element-wise comparison: [ True  True False  True  True]


In [21]:
# 3. Find Common Elements Between Two Arrays

import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Finding common elements
common_elements = np.intersect1d(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Common elements:", common_elements)

# OUTPUT : 
# Array 1: [1 2 3 4 5]
# Array 2: [4 5 6 7 8]
# Common elements: [4 5]

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Common elements: [4 5]


In [22]:
# 4. Compare Two Arrays and Find Differences

import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Finding elements in array1 that are not in array2
diff1 = np.setdiff1d(array1, array2)

# Finding elements in array2 that are not in array1
diff2 = np.setdiff1d(array2, array1)
print("Array 1:", array1)
print("Array 2:", array2)
print("Elements in array1 not in array2:", diff1)
print("Elements in array2 not in array1:", diff2)

# OUTPUT
# Array 1: [1 2 3 4 5]
# Array 2: [4 5 6 7 8]
# Elements in array1 not in array2: [1 2 3]   
# Elements in array2 not in array1: [6 7 8] 

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Elements in array1 not in array2: [1 2 3]
Elements in array2 not in array1: [6 7 8]


In [23]:
# 5. Compare Two Arrays and Find Unique Elements

import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Finding unique elements in both arrays
unique_elements = np.setxor1d(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Unique elements:", unique_elements)

# OUTPUT : 
# Array 1: [1 2 3 4 5]
# Array 2: [4 5 6 7 8]
# Unique elements: [1 2 3 6 7 8]

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Unique elements: [1 2 3 6 7 8]
